### PR TITLE
Added Capability to build on M1 Mac (tested on MacOs 11.4) with docke…

### PR DESCRIPTION
**Pull request by jeppojeps**
Changed the Dockerfile to build on M1 Macs. It may also work on Linux machines without changes. Pls check.

### CODE REVIEW

**Comment by domenukk** [comment]
Did you try building it as native aarch64? In theory it should work

**Comment by jeppojeps** [comment]
haven't done so since I found the issue to be solvable with the x86 flag, gonna try again, https://lightrun.com/answers/radian-software-riju-support-for-armm1-e-unable-to-locate-package-docker-ce-cli

**Comment by domenukk** [comment]
The flag is _very_ bad for performance, especially for JITted code like QEMU, as it's basically emulating two layers deep. Don't expect to get any performance from it. It would be better to fix it properly if it doesn't work right now.

**Comment by jeppojeps** [comment]
I know, though aarch64 doesn't work

**Comment by jeppojeps** [comment]
There's a need to change some packages within the DockerFile, and try again.

**Comment by domenukk** [comment]
Please try if #18 works for you

**Comment by jeppojeps** [comment]
doesn't work

#10 51.88     Building C extensions
#10 51.88     error: [Errno 2] No such file or directory: '/tmp/pip-install-i2ojnsbv/unicorn/../../include/unicorn'
#10 51.88     ----------------------------------------
#10 52.03 ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2ojnsbv/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2ojnsbv/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f3_1i7fd/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/unicorn Check the logs for full command output.
------
executor failed running [/bin/sh -c pip3 install -r /firmwire/requirements.txt]: exit code: 1

**Pull request closed without merging**
